src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $first_name;

    #[ORM\Column(type: 'string', length: 255)]
    private $last_name;

    #[ORM\Column(type: 'datetime_immutable')]
    private $created_at;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Lien::class, orphanRemoval: true)]
    private $lienMateriel;

    public function __construct()
    {
        $this->lienMateriel = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Lien>
     */
    public function getLienMateriel(): Collection
    {
        return $this->lienMateriel;
    }

    public function addLienMateriel(Lien $lienMateriel): self
    {
        if (!$this->lienMateriel->contains($lienMateriel)) {
            $this->lienMateriel[] = $lienMateriel;
            $lienMateriel->setClient($this);
        }

        return $this;
    }

    public function removeLienMateriel(Lien $lienMateriel): self
    {
        if ($this->lienMateriel->removeElement($lienMateriel)) {
            // set the owning side to null (unless already changed)
            if ($lienMateriel->getClient() === $this) {
                $lienMateriel->setClient(null);
            }
        }

        return $this;
    }

    public function getTotalQuantity(): int
    {
        $total = 0;
        foreach($this->getLienMateriel() as $lien) {
            $total += $lien->getQuantity();
        }
        return $total;
    }
    
    // Montant retourné en centimes
    public function getMontantTotal(): int
    {
        $total = 0;
        foreach($this->getLienMateriel() as $lien) {
            $materiel = $lien->getMateriel();
            $total += $lien->getQuantity() * $materiel->getPrice();
        }
        return $total;
    }
    
    public function __toString(): string
    {
        return $this->getFirstName().' '.$this->getLastName();
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('first_name')
            ->add('last_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/client')]
class ClientController extends AbstractController
{
    #[Route('/', name: 'app_client_index', methods: ['GET'])]
    public function index(ClientRepository $clientRepository): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_client_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ClientRepository $clientRepository): Response
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);
        $client->setCreatedAt(new \DateTimeImmutable());
        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/app_client_filtre', name: 'app_client_filtre_default', methods: ['GET'])]
    #[Route('/app_client_filtre/{nbMateriel}/{montantMateriel}', name: 'app_client_filtre', methods: ['GET'])]
    public function filtreFromNbMaterielAndMontant(ClientRepository $clientRepository, int $nbMateriel=0, int $montantMateriel=0): Response
    {
        return $this->render('client/index.html.twig', [
            'clients' => $clientRepository->findByNbMaterielAndMontant($nbMateriel, $montantMateriel),
        ]);
    }

    #[Route('/{id}', name: 'app_client_show', methods: ['GET'])]
    public function show(Client $client): Response
    {
        return $this->render('client/show.html.twig', [
            'client' => $client,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_client_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $clientRepository->add($client, true);

            return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('client/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_client_delete', methods: ['POST'])]
    public function delete(Request $request, Client $client, ClientRepository $clientRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->request->get('_token'))) {
            $clientRepository->remove($client, true);
        }

        return $this->redirectToRoute('app_client_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/client/_delete_form.html.twig
<form method="post" action="{{ path('app_client_delete', {'id': client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/client/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.first_name, {attr: {placeholder: 'Prénom du client'}, label: 'Prénom : '}) }}
    {{ form_row(form.last_name, {attr: {placeholder: 'Nom du client'}, label: 'Nom : '}) }}
    <button type="submit" class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'un client{% endblock %}

{% block body %}
    <h1>Modification d'un client</h1>

    {{ include('client/_form.html.twig', {'button_label': 'Modifier'}) }}
    {{ include('client/_delete_form.html.twig') }}
    <a href="{{ path('app_client_index') }}" class="btn btn-secondary">Retour à la liste des clients</a>

{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des clients{% endblock %}

{% block body %}
    <h1>Liste des clients</h1>

    <a href="{{ path('app_client_new') }}" class="btn btn-primary">Créer un nouveau client</a>
    <table class="table">
        <thead>
            <tr>
                <th>Identfiant</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Quantité de matériel totale</th>
                <th>Montant total</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td>
                <td>{{ client.firstName }}</td>
                <td>{{ client.lastName }}</td>
                <td>{{ client.totalQuantity() }}</td>
                <td>{{ (client.montantTotal()/100)|number_format(2, ' € ', ' ') }}</td>
                <td>
                    <a href="{{ path('app_client_show', {'id': client.id}) }}" class="btn btn-outline-secondary"><i class="bi bi-eye"></i> Voir</a>
                    <a href="{{ path('app_client_edit', {'id': client.id}) }}" class="btn btn-outline-secondary"><i class="bi bi-pencil"></i> Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun client trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un nouveau client{% endblock %}

{% block body %}
    <h1>Créer un nouveau client</h1>

    {{ include('client/_form.html.twig') }}

    <a href="{{ path('app_client_index') }}" class="btn btn-secondary" >Retour à la liste des clients</a>
{% endblock %}

templates/client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Client{% endblock %}

{% block body %}
    <h1>Client</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Identifiant</th>
                <td>{{ client.id }}</td>
            </tr>
            <tr>
                <th>Prénom</th>
                <td>{{ client.firstName }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ client.lastName }}</td>
            </tr>
            <tr>
                <th>Créé le</th>
                <td>{{ client.createdAt ? client.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_client_edit', {'id': client.id}) }}" class="btn btn-success">Modifier</a>
    {{ include('client/_delete_form.html.twig') }}
    <a href="{{ path('app_client_index') }}" class="btn btn-secondary">Retour à la liste des clients</a>


{% endblock %}