src/Entity/Lien.php
<?php

namespace App\Entity;

use App\Repository\LienRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LienRepository::class)]
class Lien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'lienMateriel')]
    #[ORM\JoinColumn(nullable: false)]
    private $client;

    #[ORM\ManyToOne(targetEntity: Materiel::class, inversedBy: 'lienClient')]
    #[ORM\JoinColumn(nullable: false)]
    private $materiel;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getMateriel(): ?Materiel
    {
        return $this->materiel;
    }

    public function setMateriel(?Materiel $materiel): self
    {
        $this->materiel = $materiel;

        return $this;
    }

    public function getMontantTotal(): int
    {
        return (int) $this->getQuantity()*$this->getMateriel()?->getPrice()/100; // Le prix est en centimes, on divise par 100 pour l'avoir en euros
    }

}

src/Form/LienType.php
<?php

namespace App\Form;

use App\Entity\Lien;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LienType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('quantity')
            ->add('client')
            ->add('materiel')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Lien::class,
        ]);
    }
}

src/Controller/LienController.php
<?php

namespace App\Controller;

use App\Entity\Lien;
use App\Form\LienType;
use App\Repository\LienRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/lien')]
class LienController extends AbstractController
{
    #[Route('/', name: 'app_lien_index', methods: ['GET'])]
    public function index(LienRepository $lienRepository): Response
    {
        return $this->render('lien/index.html.twig', [
            'liens' => $lienRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_lien_new', methods: ['GET', 'POST'])]
    public function new(Request $request, LienRepository $lienRepository): Response
    {
        $lien = new Lien();
        $form = $this->createForm(LienType::class, $lien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lienRepository->add($lien, true);

            return $this->redirectToRoute('app_lien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lien/new.html.twig', [
            'lien' => $lien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lien_show', methods: ['GET'])]
    public function show(Lien $lien): Response
    {
        return $this->render('lien/show.html.twig', [
            'lien' => $lien,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_lien_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Lien $lien, LienRepository $lienRepository): Response
    {
        $form = $this->createForm(LienType::class, $lien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $lienRepository->add($lien, true);

            return $this->redirectToRoute('app_lien_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('lien/edit.html.twig', [
            'lien' => $lien,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_lien_delete', methods: ['POST'])]
    public function delete(Request $request, Lien $lien, LienRepository $lienRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$lien->getId(), $request->request->get('_token'))) {
            $lienRepository->remove($lien, true);
        }

        return $this->redirectToRoute('app_lien_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/lien/_delete_form.html.twig
<form method="post" action="{{ path('app_lien_delete', {'id': lien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ lien.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/lien/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.quantity, {attr: {placeholder: 'Quantité'}, label: 'Quantité : '}) }}
    {{ form_row(form.client, {label: 'Client : '}) }}
    {{ form_row(form.materiel, {label: 'Matériel : '}) }}
    <button type="submit" class="btn btn-success">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/lien/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'un lien{% endblock %}

{% block body %}
    <h1>Modification d'un lien</h1>

    {{ include('lien/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_lien_index') }}" class="btn btn-secondary">Retour à la liste des liens</a>

    {{ include('lien/_delete_form.html.twig') }}
{% endblock %}

templates/lien/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des liens{% endblock %}

{% block body %}
    <h1>Liste des liens</h1>

    <a href="{{ path('app_lien_new') }}" class="btn btn-success">Créer un nouveau lien</a>
    <table class="table">
        <thead>
            <tr>
                <th>Quantité</th>
                <th>Client</th>
                <th>Matériel</th>
                <th>Montant</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for lien in liens %}
            <tr>
                <td>{{ lien.quantity }}</td>
                <td>{{ lien.client }}</td>
                <td>{{ lien.materiel }}</td>
                <td>{{ lien.montantTotal|number_format(2, ' € ', ' ') }}</td>
                <td>
                    <a href="{{ path('app_lien_show', {'id': lien.id}) }}" class="btn btn-outline-secondary"><i class="bi bi-eye"></i> Voir</a>
                    <a href="{{ path('app_lien_edit', {'id': lien.id}) }}" class="btn btn-outline-secondary"><i class="bi bi-pencil"></i> Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucun lien trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/lien/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Lien{% endblock %}

{% block body %}
    <h1>Create new Lien</h1>

    {{ include('lien/_form.html.twig') }}

    <a href="{{ path('app_lien_index') }}" class="btn btn-secondary" >Retour à la liste des liens</a>
{% endblock %}

templates/lien/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lien{% endblock %}

{% block body %}
    <h1>Lien</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Idendifiant</th>
                <td>{{ lien.id }}</td>
            </tr>
            <tr>
                <th>Quantité</th>
                <td>{{ lien.quantity }}</td>
            </tr>
            <tr>
                <th>Client</th>
                <td>{{ lien.client }}</td>
            </tr>
            <tr>
                <th>Matériel</th>
                <td>{{ lien.materiel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_lien_edit', {'id': lien.id}) }}" class="btn btn-success">Modifier</a>
    {{ include('lien/_delete_form.html.twig') }}
    <a href="{{ path('app_lien_index') }}" class="btn btn-secondary">Retour à la liste des liens</a>

{% endblock %}